[package]
name = "EPlayer"
version = "0.1.0"
description = "A English learning App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "tldrawapp_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["protocol-asset"] }
tauri-plugin-shell = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
youtube-captions = "0.1.0"
reqwest = { version = "0.11", features = ["multipart", "json"] }
rocket = "0.5.1"
tauri-plugin-log = "2"
log = "0.4"
tauri-plugin-process = "2"
base64 = "0.13"
uuid = { version = "1.0", features = ["v4"] }
md-5 = "0.10"
digest = "0.10"
tauri-plugin-dialog = "2"

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-updater = "2"
openai_api_rust = "0.1.9"
